### ISSUE TITLE
Decide what the scope of Codespaces should be for this initiative

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#10]
Should Codespaces be used for a project end-to-end — including both the data extraction and analysis steps? Or limited to the extraction step only? Only performing the data extraction steps would vastly simplify this initiative, but: asking users to switch to a different environment to continue their work might not be a great user experience, and we would not gain any insight into the usability of Codespaces to develop an analysis project end to end. 

## Tasks

1. Decide if we are investigating Codespaces for data extraction (ehrql) only, or for analysis steps
2. If we _do_ decide to investigate analysis steps, then define what step(s) will be used in this investigation
     * Programming language(s)
     * Tasks
     * Outputs
3. Decide how we might judge the success of using Codespaces to run analysis actions.

**Comment by lucyb** [comment]
This is answered in part by #23 and #9. We will cover the analyses steps, where they are included in the OpenSAFELY pipeline, if they are written in Python (and potentially R). More detailed response can be found in the proposal [here](https://docs.google.com/document/d/1-9nTMixXTY2jfece3Q7FIzP7hhX6RNtn7yT6CGdrig8/edit#heading=h.jriptmv8noem).
