### ISSUE TITLE
Determine if there are projects where Codespaces might not be suitable

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#11]
This relates to #13 which also discusses testing projects in Codespaces.

Some OpenSAFELY projects are particularly complex. Examples of these include Will's or those from the University of Bristol.

## Tasks

1. Find some suitable complex projects to run.
2. We know that Cox regressions are particularly complex. Test if Cox regressions work.
   * Do Cox regressions work at all in local environments?
3. If Codespaces is not suitable in some cases, can we create guidelines for where users should prefer local development?

## Assumptions

* We can find a project where Cox regressions converge in a local environment.

**Comment by lucyb** [comment]
I think Jon's testing has covered this very well (#13). I don't think we need to do anything further for now, especially as we've broadened the invite for user testing (#3) to include people like Will, who work on complex projects.
