### ISSUE TITLE
Review Codespaces pricing structure and available quota

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#12]
Linked to #5 .
See :thread: [conversation](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1710849485668029).

### For organisation-owned Codespaces:
See GitHub [pricing calculator](https://github.com/pricing/calculator?feature=codespaces).
A very rough estimate showed we'd be spending around $8.50 per user per month, assuming 10 hours of use per week, 10GB disk usage and one stored Codespace.

Here's a copy of the [billing report](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1710929018763129?thread_ts=1710849485.668029&cid=C069SADHP1Q) from the last three months of usage.

### Alternatively, if someone used a personal account, they would get for free:
* 120 GitHub Codespaces core hours per month per user
* 15 GB GitHub Codespaces storage per month per user

We know that we can use a basic two-cpu machine for most OpenSAFELY projects. Regarding storage quota, it seems that this is based on the machine rather than the data used by the project. So using a two-cpu machine would use 32GB of storage; however this is billed per month, so deleting the Codespace after half a month would only use 16GB of storage (I think).

### Conclusion
Assumptions ([thread](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1712070046108499)):

* we'll have organisation-owned Codespaces and that it will cost us approximately $10 per user per month ([thread](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1711722599193979?thread_ts=1711107015.313919&cid=C069SADHP1Q)).
* we'll have around 30 active users per month and around one third of active users will be using Codespaces.
* users will use Codespaces more heavily at the start of their project and less heavily near the end. We'll onboard users and projects at a consistent rate, so this usage will average out. Probably over the course of a year.

I think that's likely to be quite a high estimate, because I don't expect usage to be quite that high and it allows each user to store three Codespaces, with an average project size of 10GB, which I think is also quite generous.

Expected monthly cost is going to be around $100 per month for the OpenSAFELY GitHub organisation. So we should keep the monthly limit at $200 or even reduce it slightly, if we want to keep an eye on costs.

---

![Image](https://github.com/opensafely-core/codespaces-initiative/assets/3889554/1073b782-7c4a-4959-8793-14e4c737f1e6)

**Comment by lucyb** [comment]
From Seb (see [thread](https://bennettoxford.slack.com/archives/C069SADHP1Q/p1711722599193979?thread_ts=1711107015.313919&cid=C069SADHP1Q))

> It would not be necessary to track spending to projects, at least initially. It's quite likely to be a requirement at some point in the future.
> The $200 is, I believe, an arbitrary limit to force us to have conversations about value.
> I suggest as part of this work we:
> a) Estimate an upper limit on the costs per project
> b) Agree and document that we will pay for codespaces for all users
> c) Set a spending limit accordingly
> d) Communicate this to ops in Slack
> It would be good to have a little think about how/where we record this, so on the inevitable day in > 18 months when someone asks "should we increase this limit? Is this a lot of money" it's easy to recover the original thinking and policy.

**Comment by lucyb** [comment]
See update https://github.com/opensafely-core/codespaces-initiative/issues/5#issuecomment-2037714770

**Comment by lucyb** [comment]
I've documented this change in the team manual and I've [communicated](https://bennettoxford.slack.com/archives/C05BCDMV109/p1712323289165959) it to ops, so I believe this is now done.
