### ISSUE TITLE
Determine a recommended machine type for Codespaces

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#13]
GitHub offer several machines. These differ in [CPU core and memory size](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-github-codespaces#pricing-for-paid-usage).

Is the default 2 core machine sufficient, or are larger machine types required to avoid out-of-memory errors and similar?

Unlike some cloud computing providers, the amount of storage is not tied to the machine type: you just get billed for the storage you use. We don't have to make an upfront specification on that. However, could the storage cost be prohibitive? The free tier is 15 GB-month, calculated hourly.[^1]

## Tasks

1. Determine how we might test this out.
   * Perhaps this involves selecting some existing projects from the `opensafely` organization that currently pass the CI tests, and attempting to run them in Codespaces.
   * Should be this randomly, or a curated set of projects?
   * Should this only be restricted to projects using ehrQL, and not cohort-extractor?
2. Decide how we measure the storage use. Run a `project.yaml` in entirety and then use the GitHub-provided usage report?
   * The [CSV usage report](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/viewing-your-github-codespaces-usage#viewing-github-codespaces-usage-for-your-personal-account) does allow filtering usage by specific repository, which should help.
3. Consider [setting the decided specification](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/configuring-dev-containers/setting-a-minimum-specification-for-codespace-machines#setting-a-minimum-machine-specification) in the `devcontainer.json`. This enforces the minimum in Codespaces (not sure of effects on local dev containers?)

## Prerequisites

* This may depend on the complexity of the project in question (see #11). It might be that we don't recommend Codespaces for very complex projects.

## Assumptions

We might expect that more complex projects are more likely to be written by more experienced users, more comfortable with a local development setup.

[^1]: That is, you could have 15 GB sat in a codespace over one month, but a larger amount of storage for less time, without incurring billing.

**Comment by lucyb** [comment]
I think this issue has now been completed, thanks to @Jongmassey 's experiments. As I understand it, Jon showed that the default 2 core machine was roughly equivalent to his Windows laptop, which means it's probably sufficient for most studies, and so can be recommended as the default.

**Comment by Jongmassey** [comment]
Summary results in [this presentation](https://docs.google.com/presentation/d/1EvrZ_VOrOLUyNn4Tyqr9nafv24dddYqka9Fmzdr9cWI/edit#slide=id.g2c04a603df7_0_57)

**Comment by Jongmassey** [comment]
Bearing in mind limitations (n==1, primarily), it appears that performance was generally the same. 

Expensive actions (measures) were slightly faster in codespaces, shorter actions were slightly slower (hypothesis: slower IO means initial copy of assets into docker container are slower which on a short action is a larger proportion of the time). 

For these reasons, the _mean_ duration advantage for codespaces was ~7s but the median -1s.

From a user experience PoV - if my laptop is representative then switching to codespaces I'd experience an extra second of duration running simple ehrQL actions and several seconds less when running complex ehrQL measures actions. This feels acceptable to me.
