### ISSUE TITLE
Evaluate that Codespaces is suitable for a few different kind of laptops

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#14]
## Tasks
1. Identify some target platforms (in #1 ?) and check that GitHub say it will work: 
    * one of the Team REX
    * a very locked down Windows laptop 
    * a moderately locked down laptop.
2. Identify what NHSE  system configurations apply (See also #2.)
3. Does port forwarding when running server applications in the Codespace work (example: Jupyter)?

**Comment by lucyb** [comment]
I think we will cover this when speaking with researchers and NHSE users and I've added some extra acceptance criteria to cover it. So don't think we need a separate ticket for it now.
