### ISSUE TITLE
Evaluate whether we might want custom restrictions if we use organization-billed Codespaces 

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#16]
# Background

If it's possible that we might pay for Codespaces as mentioned in #5, we may want to use some restrictions. GitHub allows implementing various organization controls:

## Billing options

* [spending cost](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/managing-the-cost-of-github-codespaces-in-your-organization)
* [machine type](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/restricting-access-to-machine-types) (also see #13)
* [timeout period](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/restricting-the-idle-timeout-period)
* [retention period](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/restricting-the-retention-period-for-codespaces)
* [number of organization-billed codespaces per user](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/restricting-the-number-of-organization-billed-codespaces-a-user-can-create)

## Feature options

* [base image](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/restricting-the-base-image-for-codespaces)
* [port visibility](https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/restricting-the-visibility-of-forwarded-ports)

# Tasks

* Find out what the default settings are
* Consider whether we can reduce these without adversely irritating users

# Assumptions

That we're allowing using organization-billed codespaces for some or all users. This should be verified, as we may decide against this, in which case this issue is not required.

**Comment by StevenMaude** [comment]
From the discussion in #5, it does seem that organization-owned codespaces are probably the favoured option.

**Comment by lucyb** [comment]
Done. See https://bennettinstitute-team-manual.pages.dev/tech-group/playbooks/codespaces/
