### ISSUE TITLE
Investigate possibility of NHSE users working in Codespaces

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#2]
We need to validate that this is possible. Previous attempts to get NHSE users using [GitPod](https://gitpod.io) were met with difficulties around WebSockets being blocked [^1]. We believe it's quite likely that NHSE users in particular could hit problems with Codespaces.

Note: speak to Brian to help find eligible users

**Goal: figure out if NHSE users can access and use Codespaces, so that we can gain confidence that they'll be able to use it to write code for OpenSAFELY. What problems could they encounter?**

## Acceptance criteria
- [ ] One or more NHSE users are observed using Codespaces to write code for their study or the getting started guide (as appropriate).
- [ ] If Codespaces does work, then consider checking whether port forwarding will work. For example when running RStudio or Jupyter.

## Tasks
1. Ensure that the user will be able to access Codespaces.
1. Decide what we should ask the researcher to do:
   * How much of a codespace's functionality do we need to assess to be assured that it's working fine from an NHSE machine
   * Either ehrQL tutorial or doing their work in flight.. after (possibly) introducing them to Codespaces.
2. Decide how we should observe or get feedback
     * A session with someone from the REX team sitting in and observing?
3. Ascertain what the different NHSE computer specifications/configurations are that are likely to be used by users using codespaces (Modern Desktop, New Modern Desktop)
4. Recruit a researcher to participate
    * BMK, Joshua Mutio (previously copiloted by JM, has used codespaces), maybe Mark Russell(?), look on Job Server[^2][^3][^4]
6. Provide the researcher with directions on what we want them to do
7. Complete session
8. Collect feedback

[^1]: https://bennettoxford.slack.com/archives/C63UXGB8E/p1652862308620149?thread_ts=1652861311.819759&cid=C63UXGB8E
[^2]: https://jobs.opensafely.org/staff/orgs/nhsei/
[^3]: https://jobs.opensafely.org/staff/orgs/nhs-england/
[^4]: https://jobs.opensafely.org/staff/orgs/nhsx/

**Comment by lucyb** [comment]
On hold until we've started to get responses from the survey #1 .

**Comment by Jongmassey** [comment]
>Josh is on AL until 8th April but can ask (and send email with details etc) when we catch-up on the 10th April if thats not too late?

from Millie

**Comment by lucyb** [comment]
I've spoken to Brian and he's happy to spend five minutes at some point to check whether his NHS laptop (running modern desktop) on the NHS network works with Codespaces. He did point out that this might not be conclusive, as previously some NHSE users could access gitpod and some couldn't, and that we could easily request any IT restrictions be removed. It would still be a useful data point though.

We don't have to do this immediately, and could do it after we've made changes to the Getting Started Guide.

For the purpose of this ticket, it's enough to speak to Brian, and not any other NHSE users.

**Comment by lucyb** [comment]
I'll set myself a reminder to demo this to Brian in a week or two, once we have a new devcontainer config with RStudio setup.

**Comment by lucyb** [comment]
I've requested a meeting with Brian and will be talking about the work done for #43. I don't think there's anything else to do on this ticket, so I'm closing it.
