### ISSUE TITLE
Consider adding README links to start/resume a codespace

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#20]
The GitHub documentation explains [how to use the `codespaces.new` domain](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-repository/facilitating-quick-creation-and-resumption-of-codespaces) to quickly reach the codespace creation or resume options.

Since this is on a separate domain, is this generally available to users, or might it cause confusion by it not working?

**Comment by lucyb** [comment]
Given that the UI option on GitHub is easily accessible when viewing the README, I'm going to suggest that we don't do this for now. It might be something to reconsider once we've gotten some feedback from users though.
