### ISSUE TITLE
Observe Tom O using Codespaces to complete the ehrQL getting started guide

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#27]

**Comment by iaindillingham** [comment]
See:
* opensafely/ehrql-tutorial#2
* opensafely/ehrql-tutorial#3
* [Tom going through the ehrQL Tutorial][1]

[1]: https://docs.google.com/document/d/1GJel2Sf8MnZckdVst2ZrUSzj4Kj76CgTxeX-aBWLoMU/edit#heading=h.g1syc81zt77t

**Comment by Jongmassey** [comment]
https://github.com/opensafely/documentation/issues/1458

**Comment by lucyb** [comment]
This was really interesting, thank you! It's great that you've been able to improve the docs as a result. I'm also interested that Tom was just able to drag and drop files into the Codespace, that seems very helpful for some use cases.
