### ISSUE TITLE
Try Codespaces with existing ehrQL studies

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#28]
We should see how Codespaces behaves when running ehrQL actions for existing studies. We believe this will give us a useful and representative set of studies that will give us a very good indication about whether Codespaces can be reasonably used, since having an ehrQL action will be essential for all of them. It will also help provide us with an indication of the limitations of Codespaces and when it might not be appropriate.

We should use the default, 2-CPU machine type, which is the cheapest available for Codespaces and see how they perform (at least to start with). This will provide us with useful information for when we come to write our policy on Codespace usage.

We should select all, or a random sample, of studies that have successfully run an ehrQL action in production. This should be less than 20 in total.

**Comment by Jongmassey** [comment]
Initial noodlings and local run results https://github.com/opensafely/codespaces_ehrql_performance_evaluation/pull/1

**Comment by Jongmassey** [comment]
[Presentation ](https://docs.google.com/presentation/d/1EvrZ_VOrOLUyNn4Tyqr9nafv24dddYqka9Fmzdr9cWI/edit?usp=sharing) from tech team meeting with results.

Detailed results in linked PR.
