### ISSUE TITLE
Get an existing OpenSAFELY researcher to try Codespaces

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#3]
We would like to see what happens if an existing researcher tries to write code within Codespaces.

What difficulties do they find when trying to work in Codespaces, as compared with their local setup?

## Tasks

1. Decide what we should ask the researcher to do:
   * ~Is this to run through the ehrQL tutorial or OpenSAFELY Getting Started?~
   * Is this to work on an existing project? Do we have any view on the "complexity" of such a project to try? [^1]
1. Recruit a researcher to participate
1. Provide the researcher with directions on what we want them to do
1. Decide how we should observe or get feedback
   * An entirely "offline" session with the researcher giving feedback afterwards?
   * A session with someone from the REX team sitting in and observing?
   * A session where the researcher records themselves, maybe in Meet or similar, talking out loud while they work?
   * Something else?
1. Complete the session
1. Evaluate what went well, and any problems that arose; are these problems issues that are fixable, or limitations of Codespaces?
   * Did they need much, if any, Linux knowledge to do their work? Codespaces run in a Linux virtual machine. Ideally, we don't want researchers to have to understand much, if anything, of how Linux works to develop their code.

## Prerequisites

If the researcher hasn't used Codespaces before with OpenSAFELY, this might require:

* either some of the Codespaces documentation reviewing, refining or tidying up first (#6)
* or a short 15-20 minute session with someone from the REX team to run through how Codespaces works with the researcher

If this is for an existing project that was started before we added the devcontainer configuration to the research-template, the researcher may also need to add this configuration to their project.

[^1]: We're also considering issues with more complex OpenSAFELY projects in #11.

**Comment by lucyb** [comment]
Note: we could consider contacting an external researcher, like someone from the Uni of Manchester who's previously had problems running OpenSAFELY.

**Comment by lucyb** [comment]
On hold until we've started to get responses from the survey #1 .

**Comment by lucyb** [comment]
We've learned from the survey that Helen is having significant issues with her local setup, so we should approach her and see if Codespaces can help. This will give us valuable information about where Codespaces is useful (i.e can it be used for general development or is it just useful for getting started)

**Comment by Jongmassey** [comment]
I'm going to have a session with Helen w/c 1st April

**Comment by Jongmassey** [comment]
[Broadened invite](https://bennettoxford.slack.com/archives/C02HJTL065A/p1711112194014739)

**Comment by Jongmassey** [comment]
@wjchulme  is keen, I'll try and get a date in the diary

**Comment by lucyb** [comment]
We met with Will this afternoon. He seemed interested in the potential of running devcontainers locally, as that would provide him with an R/RStudio setup that mirrored the OpenSAFELY R image. I said I'd raise a PR against this [repo](https://bennettoxford.slack.com/archives/C02HJTL065A/p1712932723503309?thread_ts=1711112194.014739&cid=C02HJTL065A) with a devcontainers config, once we have one that's ready for him to try.

He did mention that he'd be less likely to use `opensafely run` as a result of having a better R development environment, which is something we should be aware of in future, as researchers should still run it regularly.

Will said that he uses GitHub Desktop for R, but does sometimes commit via VS Code.

He really liked being able to use Codespaces when reviewing a recent change to the team manual 🎉 .

**Comment by lucyb** [comment]
I've messaged Will with details of how he can try out devcontainers locally and raised a [PR](https://github.com/opensafely/comparative-booster-spring2023/pull/10) against his repo.

**Comment by lucyb** [comment]
I'm closing this as we've completed discovery now. I've [written up](https://docs.google.com/document/d/1Jz11t-JLjL02_eLkynMvfU05-IhQfnhbmdTbaAyiJbk/edit) my session watching Rose use Codespaces. Future user testing will probably be focused on testing out the changes to the devcontainers configuration or the documentation, so covered under those tickets.
