### ISSUE TITLE
Remove extraneous notifications for Codespaces 

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#31]
By removing unnecessary notifications in Codespaces, we can make it simpler for a user to follow a Codespaces setup — because there are fewer potential distractions and decisions to make — and it reduces the amount of explanation we need in our documentation

## Tasks

During #4, we noticed a couple of distracting VSCode notifications that appear in the process of completing the Getting Started guide:

- [x] deprecated linting and formatting settings for Python (added in https://github.com/opensafely/research-template/pull/117)
- [ ] "do you want to periodically run `git fetch`"?

The relevant OpenSAFELY documentation (#6) should also be reviewed to see if we can remove text alluding to notifications that we remove. This is most likely the Getting Started guide (#30).

We should aim to minimise any other notifications like this if we spot them.

**Comment by Jongmassey** [comment]
Alternatively, I think both of these could be silenced by changing the vs code settings file in the research template?

**Comment by StevenMaude** [comment]
> Alternatively, I think both of these could be silenced by changing the vs code settings file in the research template?

That's a nice idea. And there is a "do not disturb" mode that acts a more global toggle. But I can't find anything in the [`settings.json`](https://code.visualstudio.com/docs/getstarted/settings#_default-settings) to configure "do not disturb" as default, unfortunately.

Setting a `git.autofetch` option might silence that related notification though.

**Comment by lucyb** [comment]
Added here https://github.com/opensafely/research-template/pull/117
