### ISSUE TITLE
Decide how dev container Docker base image gets its version pinned and upgraded

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#35]
* How do we decide on when to upgrade the image version in the template?
* Should we encourage users who have already created repositories based on the research template to upgrade?
* Should the OpenSAFELY CLI handle this somehow?

**Comment by StevenMaude** [comment]
If we're using a custom Dockerfile, rather than specifying an image in the `devcontainer.json`, then I think it might be possible to get Dependabot to check for new versions of that image.

**Comment by lucyb** [comment]
This will now be covered as part of https://github.com/opensafely-core/codespaces-initiative/issues/43
