### ISSUE TITLE
Decide on Visual Studio Code auto save configuration

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#36]
In some instances, a frequent autosave may not be desirable; for example, where you have a site that rebuilds on every save.

For the research-template, this may or may not be OK.

Auto save is controlled via a JSON setting.

**Comment by StevenMaude** [comment]
~It seems like you can set the setting as follows in `devcontainer.json`, but that "remote" setting gets overridden by the workspace settings:~

```json
        "customizations": {
                "vscode": {
                        "settings": {
                                "files.autoSave": "off"
                        }
                }
         }
```

Actually, I *think* this works. The actual setting state is very confusing, because there are multiple levels of setting (user, workspace, remote…) and, I'm not entirely sure but I think, "Auto save" might be ticked in the menu bar, yet possibly disabled even?!

For reference, the other location you can add such settings is `.vscode/settings.json`.

Disabling autosave entirely may not be what we want though:

* GitHub Codespaces mentions that you should enable autosave when working in local VSCode connected to a codespace, which I guess is to ensure you don't lose anything on a disconnect
* It might be that setting a moderate delay is preferable, for instances where servers are likely to be running to prevent continuous triggering of rebuilds; a user can always manually save with `Ctrl+S`; example: `"files.autoSaveDelay": 60000`
* There are [other options](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save) when the editor loses focus, which might also be suitable.
* microsoft/vscode#45997 suggests that format on save doesn't work when auto save is enabled; may need investigating and may also be a consideration/something else to solve

**Comment by StevenMaude** [comment]
Now that we know that auto save is configurable in Codespaces, what I think needs to be decided to close this are:

1. Do we want auto save enabled?
   * Probably yes, as avoiding losing user work —  or losing relatively little, only the changes since the last auto save — should be a priority.
   * I'm not entirely sure on the failure mode when there's a sudden disconnection or Codespaces outage, but [GitHub's own documentation](https://docs.github.com/en/codespaces/getting-started/understanding-the-codespace-lifecycle#saving-changes-in-a-codespace) recommends enabling auto save when using Codespaces with a _local_ Visual Studio Code editor:
     > When you connect to a codespace through Visual Studio Code running on your desktop, you must enable auto-save.
   * The downside of this is that any running "live" servers that rerun code based on changes to source files may run frequently.
1. How should auto save be configured? The [options](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save) are:
   * time delay
   * focus change away from the unsaved file
   * focus change away from the Visual Studio Code window (_does this feature work, and how does this work in Codespaces? when you navigate to a new tab/away from the browser window?_)
1. Do we want "auto format on auto save" to work? This would require different tools for Python and R.

Finally, it will be useful to confirm that any settings changes added behave as intended in a codespace. The hierarchy of Visual Studio Code settings can be a little complex, especially with the extra "Remote" level added by Codespaces/dev containers.

***

For projects that only actually run code when `opensafely run`, then the answers might be:

1. Yes, auto save should be enabled.
1. Auto saving whether immediately or on delay may be OK.
1. We might want to make "auto format on auto save" work. However, we also need to review the existing formatting tooling, because it's deprecated (#31). That in turn requires a decision on whether we even want formatting tooling bundled in.

**Comment by lucyb** [comment]
I'm closing this, because after testing it appears that autosave has been enabled and this isn't causing any problems with the user experience/performance.
