### ISSUE TITLE
Move the instructions for local installation that are interleaved with Codespaces from the Getting Started page.

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#39]
We already have separate installation instructions for Mac, so we should move the Windows installation instructions out of the Getting Started Guide and into a separate page.

This does not include fixing any problems with either the Getting Started Guide or the installation instructions. Those should be addressed in separate issues.

Dependent on #40

**Comment by StevenMaude** [comment]
We may well replace the tutorial entirely. But as an incremental improvement, this still makes sense to do, to move out installation information that still may be useful, to have a simpler tutorial in the meantime, and to better reflect what the future structure of the tutorial might be.

**Comment by iaindillingham** [comment]
I think the following PRs allow us to close this issue:

* opensafely/documentation#1478
* opensafely/documentation#1485
