### ISSUE TITLE
Observe Catherine using Codespaces to complete the main OpenSAFELY Getting Started guide

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#4]
This is a similar task to #3, but looking at the Getting Started guide only.

## Tasks

1. ~Recruit a researcher to participate~ Book some time in with Catherine
1. Provide the Catherine with directions on what we want her to do to complete the Getting Started Guide
1. Decide how we should observe or get feedback
   * ~An entirely "offline" session with the researcher giving feedback afterwards?~
   * A session with someone from the REX team sitting in and observing?
   * ~A session where the researcher records themselves, maybe in Meet or similar, talking out loud while they work?~
1. Conduct the session
1. Evaluate what went well, and any problems that arose; are these problems issues that are fixable, or limitations of Codespaces?
   * Did she need much, if any, Linux knowledge to do their work? Codespaces run in a Linux virtual machine. Ideally, we don't want researchers to have to understand much, if anything, of how Linux works to develop their code.
   * How did she view the histogram that was generated at the end? How do we manage outputs as part of using Codespaces?

~## Prerequisites~

~If the researcher hasn't used Codespaces before with OpenSAFELY, this might require:~ 

~* either some of the Codespaces documentation reviewing, refining or tidying up first (#6)~ 
~* or a short 15-20 minute session with someone from the REX team to run through how Codespaces works with the researcher~ 

~If this is for an existing project that was started before we added the devcontainer configuration to the research-template, the researcher may also need to add this configuration to their project.~

**Comment by lucyb** [comment]
Before contacting users we should time how long it takes to complete the Getting Started Guide in Codespaces ourselves. If it's very quick, we may want to roll this task into #3.

EDIT: it took me around 30 mins to complete the guide ( see #26 ).

EDIT: I've updated the description to specify that we're doing this session specifically with Catherine. We should wait until the results of the survey before we decide whether it's worth contacting other users.

**Comment by StevenMaude** [comment]
We've completed a session with Catherine that gave us a lot of [useful feedback](https://docs.google.com/document/d/1m8wOq-Vb_9gd5ki4it3jYuYEFZWrulh9ET36SjdvqTU/edit), both on Codespaces itself, and on improving the Getting Started guide with a view to making it primarily for Codespaces.

Overall, Codespaces worked here to run through the Getting Started guide.

I've written up:

* potential improvements to the Getting Started guide in #30
* a couple of potential improvements to simplify interaction with Codespaces in #31

**Comment by StevenMaude** [comment]
With the notes we made, and the newly opened issues, I believe this is complete.

There weren't any immediate blockers with Codespaces. #30 and #31 do note some potential usability improvements.

To answer specific questions in the opening comment:

> Did she need much, if any, Linux knowledge to do their work? Codespaces run in a Linux virtual machine. Ideally, we don't want researchers to have to understand much, if anything, of how Linux works to develop their code.

No, everything worked without needing to do anything much at the terminal except run `opensafely` commands.

> How did she view the histogram that was generated at the end? How do we manage outputs as part of using Codespaces?

The histogram could be viewed by double-clicking on it in the Visual Studio Code File Explorer. The `csv.gz` outputs did require using `opensafely unzip output` as the Getting Started guide mentions.
