### ISSUE TITLE
Test Codespaces with Viyaasan

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#49]
Viyaasan's said that his "computer becomes unbearably slow when Docker desktop is open". We believe that Codespaces can help.

Can someone get in touch with Viyassan before Fri 3rd May to explain that we'll be able to provide him with some more instructions in a few weeks.

We should aim to provide Viyaasan with an updated config and some documentation before 17th May or contact him to let him know this has been delayed.

**Comment by lucyb** [comment]
I sent Viyaasan a DM this afternoon and cc'd Jon, just to let him know we are planning to provide him with instructions for getting setup with Codespaces in 1-2 weeks.

**Comment by Jongmassey** [comment]
DM'd to say we'd be in touch next week to help get started

**Comment by Jongmassey** [comment]
[Linked to latest docs in open channel](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1715604511112589)

**Comment by iaindillingham** [comment]
Vi reached the "[Approve and merge the pull request](https://docs.opensafely.org/getting-started/how-to/add-github-codespaces-to-your-project/#approve-and-merge-the-pull-request)" section, but GitHub reported "Pull request authors can’t approve their own pull request". I'm sure that I've approved my own PRs on other repos, so we should investigate whether:

* this is a restriction on this specific repo
* this is a restriction on all opensafely repos
* I have a poor memory

**Comment by Jongmassey** [comment]
To keep him moving, I've approved this PR

**Comment by Jongmassey** [comment]
https://github.com/opensafely-core/research-template-docker/issues/27 This issue arose during Vi's first attempts to use the codespace.

**Comment by lucyb** [comment]
I've had a look at the settings on that repo and I believe it just has the standard setup (I think Bristol have slightly different and stricter settings). There doesn't seem to be anything that would require someone to approve Vi's PR. I think he should simply be able to merge it himself (he won't be able to approve it, but that doesn't seem necessary).

Perhaps we've made some assumptions about how most (but not all) researchers use GitHub and can simplify the instructions slightly?

**Comment by iaindillingham** [comment]
> Perhaps we've made some assumptions about how most (but not all) researchers use GitHub

Almost certainly! However, I don't think we can unpick them without observing researchers using GitHub. When we speak to co-pilots (#60) we can ask whether we can watch one or two of them walk through "[How to add GitHub Codespaces to your project](https://docs.opensafely.org/getting-started/how-to/add-github-codespaces-to-your-project/)".

**Comment by iaindillingham** [comment]
Closing, because Vi hasn't had a chance to look at Codespaces yet. If he gets the chance, then we can repoen.
