### ISSUE TITLE
Test Codespaces with Em Prestige

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#50]
Em is having trouble with R package versions and we believe Codespaces will help.

The repo is https://github.com/emprestige/disparities-comparison. 

Slack 🧵 [thread](https://bennettoxford.slack.com/archives/C010SJ89SA3/p1714136293726189).

I said I'd provide an updated config by 3rd May. If this isn't possible, I'll write her a note in slack to explain.

**Comment by lucyb** [comment]
I've left Em a slack message to let her know we expect to be able to get her setup with Codespaces / the latest dev containers config by Friday 10th May. I've said that @Jongmassey  will be able to pass on the details. This could be a PR with a simple set of instructions or it could be the new documentation page with a more detailed set of instructions for how Em can set it up herself, either way we should expect, and actually invite, questions / feedback.

**Comment by Jongmassey** [comment]
DM'd to say we'd be in touch next week to help get started

**Comment by Jongmassey** [comment]
[Linked to latest docs in open channel](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1715604511112589)

**Comment by iaindillingham** [comment]
Em is going to use Codespaces when her project is moved to the opensafely org.

**Comment by iaindillingham** [comment]
I'm going to remove this from Blocked and mark it as closed. We can create a new issue (or reopen this issue) when Em is ready to move her repo to the opensafely org.
