### ISSUE TITLE
Rebuild dev container docker image weekly

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#52]
The R image and sometimes the Python image have new packages added to them fairly regularly. To ensure we pick up these changes, and also stay on top of any security updates from rocker, we should rebuild the docker image regularly.

Rebuilding the image weekly, means that we'll pick up any new packages within a reasonable amount of time.

## TODO

- [ ] Update the existing CI workflow to run automatically each week ([docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule))

> [!NOTE]
> GitHub disable scheduled workflows if no changes are made to a repo in 60 days. Please ignore that problem for this ticket.

**Comment by StevenMaude** [comment]
Note that scheduled workflows interact with the last user who edited the cron line:

* failure notifications go to that user, although we can redirect failures to Slack if we add an action to do that (I knew this caveat)
* the workflow gets disabled if that user leaves the organization (I didn't know this caveat)

**Comment by lucyb** [comment]
That's a good point Steve. We should definitely make sure failure notifications go into Slack as part of this ticket.

We shouldn't worry about someone leaving as part of this ticket. Although if it becomes an issue in future, there are third-party services that can alert us if a cron job doesn't run, which could also work with scheduled workflows.
