### ISSUE TITLE
Add a customised MOTD in Codespaces

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#53]
We think that it would be helpful to provide a customised MOTD in the terminal for people using Codespaces.

This could tell them they're using an OpenSAFELY environment and how to get help if needed. It should also remind them about regularly running `opensafely exec` and `opensafely run`.

**Comment by iaindillingham** [comment]
We will add one MOTD that realates to `exec` and `run`. We will create another issue for adding further messages.
