### ISSUE TITLE
Tag dev container Docker image as v0

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#58]
- [x] Update the CI in research-template-docker to tag the image as v0 as well as latest.
- [x] Update the devcontainer.json to v0 away rather than latest.

**Comment by Jongmassey** [comment]
I believe this is all done based on the code [here](https://github.com/opensafely-core/research-template-docker/blob/main/.github/workflows/main.yml#L71-L76) having been merged in [this PR](https://github.com/opensafely-core/research-template-docker/pull/11). Do you agree @iaindillingham  ?

**Comment by iaindillingham** [comment]
Yes, agreed. Thanks, @Jongmassey.
