### ISSUE TITLE
Review all OpenSAFELY documentation relating to Codespaces

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#6]
Currently, these are:

* the [Getting Started guide](https://docs.opensafely.org/getting-started/)
* the [ehrQL tutorial](https://docs.opensafely.org/ehrql/tutorial/) (owned by the RAP team)
* the [general Codespaces guidance](https://docs.opensafely.org/github-codespaces/)

## Tasks

This will require :

1. Establish standards by which the documentation will be judged
    * Is all the codespaces related documentation in these three places necessary?
    * Is all the codespaces related documentation up to date and accurate?
    * Is all the codespaces related documentation complete?
2. Assessing the documentation in these three places
3. Recording where the documentation is not up to standard
4. Improving the documentation such that it is up to standard

**Comment by StevenMaude** [comment]
We've run through the Getting Started guide in #4, which has given several suggestions for improving and refining that guide, if we want others to run through it with Codespaces.

**Comment by lucyb** [comment]
I believe we've now reviewed the documentation as part of our internal user research and identified areas for improvement. We should make the improvements as part of the development phase, so I'm closing this discovery ticket.
