### ISSUE TITLE
Blog: Use of Codespaces

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/codespaces-initiative#62]
Requires #60 to be completed first.

We should write a blog post about our use of Codespaces 

** This needs further refinement **

> [!Note]
See the team manual for the process of developing a blog post.

**Comment by Jongmassey** [comment]
An interesting aspect of Codespaces is that they bring a lot of the benefits of a "Remote desktop based TRE" (preconfigured environements) without the downsides (cost of infrastructure, access to private data - if applicable) .
