### ISSUE TITLE
Discuss our plans for Codespaces with OpenSAFELY copilots

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/codespaces-initiative#7]
We want to know what copilots think about an intended move to Codespaces as a default first configuration for OpenSAFELY users. We also want "buy-in" from them for our plans. It's possible our changes may require changes from them or updates to their documentation, if so we want to make sure this is okay as early as possible.

>[!Note]
> The Copilots onboarding docs are [here](https://drive.google.com/drive/folders/18gossm8QR950YLb-rZWyA27JLxFTqHcZ).

## Tasks

1. Decide how we want to get feedback. Ideas:
   * Discuss on Slack.
   * Speak to a few people individually
   * Speak to a group.
1. Explain what Codespaces is, and what it does.
   * Should this involve a quick demo?
1. Describe our current intent is with Codespaces. This might require that we have:
   * a summary of what our current idea is
   * an explanation of how Codespaces might help users get working on OpenSAFELY projects more quickly
   * a rough schedule for implementation
1. It might also be useful to get feedback on the current issues with the development setups of users that copilots have had to solve, to see what problems we could solve with Codespaces.
   * Do copiloted users always have a development setup for working with OpenSAFELY by the time copiloting starts? 
   * Have copilots had to provide technical support for issues with setups of users?
   * Are there frequent issues that arise?
   * Might the availability of a reproducible codespace or [Live Share of a codespace a researcher is working in](https://docs.github.com/en/codespaces/developing-in-a-codespace/working-collaboratively-in-a-codespace) maybe help with debugging problems? 
1. Would any changes be disruptive to them?

## Prerequisites

* That we have an idea of what we're planning with Codespaces. From the initiative document, that's currently:
  > Move to a Codespaces-first development experience for the majority of users, so that researchers can more quickly and easily progress from the getting started guides through to running their first job.
  > …
  > Researchers who want to work locally are able to follow a documented path to move away from Codespaces if they wish.

**Comment by lucyb** [comment]
We've spoken with the copilots, so they know what we're doing in the discovery part of the initiative. We should continue to keep them informed and should let them know about what we decide we're going to do for the development phase.
