### ISSUE TITLE
Add a "Troubleshooting Codespaces" page

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/codespaces-initiative#71]
Several users have reported issues that are slightly too small to address, but slightly too large to ignore. We should add a "Troubleshooting Codespaces" page, to collect these issues. We don't expect users to read the page, as such; instead, we expect users to ask tech support for help, and for tech support to point users to the relevant section of the page.

There doesn't seem to be a good home for a troubleshooting section within the [Diátaxis](https://diataxis.fr/) framework. Also, there isn't a dedicated Codespaces section in the docs: most (all?) of our Codespaces content lives within the "Getting started" section. For these reasons, I'd suggest adding "Troubleshooting Codespaces" as a subsection of the "[How-to guides](https://docs.opensafely.org/getting-started/how-to/)" section, but without the "How to" prefix.

Sections of the page:

* RStudio displays an "R Session Error" when the associated Codespace is stopped and restarted (see below). Thank you for reporting this, @rose-higgins.

* RStudio's working directory isn't always set to the workspace directory.
  opensafely/research-template#130

* RStudio's Git dropdown and tab isn't displayed without [an RStudio project file](https://support.posit.co/hc/en-us/articles/200526207-Using-RStudio-Projects). Thank you for reporting this, @milanwiedemann.
  opensafely-core/research-template-docker#48

* Committing `ehrql-main` is easy, but incorrect. Thank you for reporting this, @alschaffer.
  opensafely/research-template#135

* GitHub displays "This codespace is requesting additional permissions" when starting a new Codespace (see below).

* Synchronising VS Code settings (see below).

## "R Session Error"

Steps to reproduce:

* Start a Codespace
* Start an RStudio session
* Stop the Codespace
* Restart the Codespace
* Refresh the RStudio session

![R Session Error](https://github.com/opensafely-core/codespaces-initiative/assets/477263/46829b16-3b10-438a-8ccf-8bc862f2b2e8)

## "This codespace is requesting additional permissions"

[opensafely/server-instructions](https://github.com/opensafely/server-instructions) contains the Stata license. Every member of the opensafely GitHub organisation can authorise the request; only those who plan to use Stata need do so.

![This codespace is requesting additional permissions](https://github.com/opensafely-core/codespaces-initiative/assets/477263/02df2ec3-2582-4771-b2e2-8b96937e68ef)

## Synchronising VS Code settings

Rather than add all the VS Code plugins a researcher could possibly need to Codespaces, it would be better for each researcher to choose their own VS Code plugins, and for their choices to be propagated through "[Settings Sync](https://code.visualstudio.com/docs/editor/settings-sync)".[^1]

[^1]: https://bennettoxford.slack.com/archives/C02HJTL065A/p1718628853531489

**Comment by Jongmassey** [comment]
I wonder if we might not want to be so explicit as 

>[opensafely/server-instructions](https://github.com/opensafely/server-instructions) contains the Stata license.

maybe
>Read permissions for [opensafely/server-instructions](https://github.com/opensafely/server-instructions) are required to make Stata work.

**Comment by Jongmassey** [comment]
I don't know how important it is that we maintain the conceit that we're not distributing the stata license key to all members of the opensafely org in the clear.
